CREATE TABLE model_call_audit (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL COMMENT 'platform trace id',
    biz_scene VARCHAR(64) NULL COMMENT 'business scene, e.g. topic_suggestion/codegen',
    provider VARCHAR(64) NOT NULL DEFAULT 'dashscope',
    endpoint VARCHAR(64) NOT NULL COMMENT 'chat.completions / embeddings',
    model_name VARCHAR(128) NOT NULL,
    upstream_request_id VARCHAR(128) NULL COMMENT 'x-request-id from upstream provider',
    user_id VARCHAR(64) NULL,
    client_platform VARCHAR(32) NULL,
    app_version VARCHAR(64) NULL,
    device_id VARCHAR(128) NULL,
    stream TINYINT(1) NOT NULL DEFAULT 0,
    success TINYINT(1) NOT NULL DEFAULT 0,
    http_status INT NULL,
    latency_ms INT NOT NULL DEFAULT 0,
    token_input INT NULL,
    token_output INT NULL,
    token_total INT NULL,
    request_body MEDIUMTEXT NULL,
    response_body MEDIUMTEXT NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(512) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_model_call_audit_trace_id (trace_id),
    INDEX idx_model_call_audit_model_created (model_name, created_at),
    INDEX idx_model_call_audit_endpoint_created (endpoint, created_at),
    INDEX idx_model_call_audit_success_created (success, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Model gateway call audit log';
